"""Add nutritional information

Revision ID: 07d7883b354c
Revises: 97cc0ebfa8ed
Create Date: 2024-10-04 15:05:44.262560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "07d7883b354c"
down_revision: Union[str, None] = "97cc0ebfa8ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutritionalinformation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("calories", sa.Float(), nullable=True),
        sa.Column("total_fat", sa.Float(), nullable=True),
        sa.Column("saturated_fat", sa.Float(), nullable=True),
        sa.Column("polyunsaturated_fat", sa.Float(), nullable=True),
        sa.Column("monounsaturated_fat", sa.Float(), nullable=True),
        sa.Column("trans_fat", sa.Float(), nullable=True),
        sa.Column("total_carbohydrate", sa.Float(), nullable=True),
        sa.Column("dietary_fiber", sa.Float(), nullable=True),
        sa.Column("total_sugars", sa.Float(), nullable=True),
        sa.Column("protein", sa.Float(), nullable=True),
        sa.Column("salt", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nutritionalinformation")
    # ### end Alembic commands ###
