"""Create extracted ticket info table

Revision ID: 783f148d39eb
Revises: feff058e9105
Create Date: 2024-10-22 19:54:52.355993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "783f148d39eb"
down_revision: Union[str, None] = "feff058e9105"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket",
        sa.Column("ticket_number", sa.Integer(), nullable=True),
        sa.Column("date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticketitem",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column(
            "matched_product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["matched_product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticketitem")
    op.drop_table("ticket")
    # ### end Alembic commands ###
